def gettext(s):
    return s


class DjangoSettings(object):
    """
    Django settings for a_pycon_story project.

    Generated by 'django-admin startproject' using Django 3.2.13.

    For more information on this file, see
    https://docs.djangoproject.com/en/3.2/topics/settings/

    For the full list of settings and their values, see
    https://docs.djangoproject.com/en/3.2/ref/settings/
    """

    from pathlib import Path

    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR = Path(__file__).resolve().parent.parent

    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = "django-insecure-0wiuafct*3#_p4ak*=wns=v4omllvus&2_ydft_0khu^j7i_8q"

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = True

    ALLOWED_HOSTS = []  # type: ignore

    # Application definition

    INSTALLED_APPS = [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
    ]

    MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
    ]

    ROOT_URLCONF = "a_pycon_story.urls"

    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": [],
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.debug",
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                ],
            },
        },
    ]

    WSGI_APPLICATION = "a_pycon_story.wsgi.application"

    # Database
    # https://docs.djangoproject.com/en/3.2/ref/settings/#databases

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

    # Password validation
    # https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

    # Internationalization
    # https://docs.djangoproject.com/en/3.2/topics/i18n/

    LANGUAGE_CODE = "en-us"

    TIME_ZONE = "UTC"

    USE_I18N = True

    USE_L10N = True

    USE_TZ = True

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/3.2/howto/static-files/

    STATIC_URL = "/static/"

    # Default primary key field type
    # https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

    DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


class UserSettings(object):
    AUTH_USER_MODEL = "profiles.User"

    LOGIN_URL = "/admin/login/"  # reverse_lazy('auth:login')

    LOGOUT_URL = "/admin/logout/"  # reverse_lazy('auth:logout')

    LOGIN_REDIRECT_URL = "/"


class RestFrameworkSettings(object):
    # https://github.com/encode/django-rest-framework/blob/master/rest_framework/settings.py
    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": (
            # 'rest_framework.authentication.TokenAuthentication',
            # 'rest_framework.authentication.BasicAuthentication',
            # 'rest_framework.authentication.SessionAuthentication',
        ),
        #  Use Django's standard `django.contrib.auth` permissions,
        #  or allow read-only access for unauthenticated users.
        "DEFAULT_PERMISSION_CLASSES": (
            "rest_framework.permissions.AllowAny",
            # 'rest_framework.permissions.IsAdminUser',
            # 'rest_framework.permissions.IsAuthenticated',
            # 'rest_framework.permissions.DjangoModelPermissions',
            # 'rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly',
        ),
        "DEFAULT_RENDERER_CLASSES": [
            "rest_framework.renderers.JSONRenderer",
        ],
        # "EXCEPTION_HANDLER": "",
        # ===============================================================================
        #     'DEFAULT_MODEL_SERIALIZER_CLASS':
        #         'rest_framework.serializers.ModelSerializer',
        #
        #     'DEFAULT_RENDERER_CLASSES': [
        #         'rest_framework.renderers.BrowsableAPIRenderer',
        #         'rest_framework.renderers.JSONRenderer'
        #     ],
        #     'DEFAULT_PARSER_CLASSES': [
        #         'djangorestframework_camel_case.parser.CamelCaseJSONParser',  # Any other parsers
        #         'rest_framework.parsers.FormParser',
        #         'rest_framework.parsers.MultiPartParser',
        #     ],
        #
        #     # 'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
        #     # 'DEFAULT_PAGINATION_CLASS': 'a_pycon_story.api.pagination.StandardResultsSetPagination',
        #     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
        #     'PAGE_SIZE': 100,
        #     'SEARCH_PARAM': 'q',
        #
        #     'EXCEPTION_HANDLER':'a_pycon_story.api.views.anyplan_exception_handler',
        #     'EXCEPTION_HANDLER':'rest_framework.views.exception_handler',
        #
        # ===============================================================================
    }

    # ===============================================================================
    # REST_FRAMEWORK_EXTENSIONS = {
    #     'DEFAULT_OBJECT_ETAG_FUNC': 'a_pycon_story.utils.custom_object_etag_func',
    #     'DEFAULT_LIST_ETAG_FUNC': 'a_pycon_story.utils.custom_list_etag_func',
    # }
    # ===============================================================================

    REST_FRAMEWORK_VALIDATION_STATUS_CODE = 400


class RosettaSettings(object):
    ROSETTA_STORAGE_CLASS = "rosetta.storage.CacheRosettaStorage"
    ROSETTA_UWSGI_AUTO_RELOAD = True
    ROSETTA_WSGI_AUTO_RELOAD = True
    ROSETTA_MESSAGES_PER_PAGE = 50


class ShellPlusSettings(object):
    SHELL_PLUS = "ipython"

    SHELL_PLUS_POST_IMPORTS = [
        # ('module.submodule1', ('class1', 'function2')),
        # ('module.submodule2', 'function3'),
        "os",
        "re",
        "datetime",
        "pytz",
        "random",
        # ("fhcore.utils.urls_utils", ("make_absolute_url",)),
    ]


class StorageSettings(object):
    FILE_UPLOAD_PERMISSIONS = 0o644
    FILE_UPLOAD_DIRECTORY_PERMISSIONS = 0o755

    DATA_UPLOAD_MAX_MEMORY_SIZE = 26214400  # i.e. 25 MB
    DATA_UPLOAD_MAX_NUMBER_FIELDS = None


class DjangoCMSSettings(object):

    from django.utils.translation import ugettext, ugettext_lazy as _  # noqa

    # Django-CMS settings
    """
    CMS_MENU_TITLE_OVERWRITE = True # (default)
    CMS_MEDIA_URL = '/media/cms/'
    CMS_MEDIA_ROOT = os.path.join(STATIC_ROOT, 'cms/')
    CMS_PAGE_MEDIA_PATH = os.path.join(MEDIA_ROOT, 'uploads', 'cms_page_media')
    """

    CMS_PERMISSION = True

    CMS_TEMPLATES = (
        ("cms_templates/blank.html", "Pagina Descrittiva"),
        ("cms_templates/generic.html", "Pagina Generica"),
    )

    CMS_PLACEHOLDER_CONF = {
        "generic": {
            "plugins": [
                "RedactorTextPlugin",
            ],
            # 'CharFieldPlugin', 'TextFieldPlugin', 'LinkPlugin',
            "name": _("Placeholder Generico"),
        },
    }
    # CMS_APPLICATIONS_URLS = ( )
    # CMS_NAVIGATION_EXTENDERS = ( )

    CMS_LANGUAGES = {
        1: [
            {
                "code": "en",
                "name": _("English"),
                "fallbacks": [],
                "public": True,
                "hide_untranslated": True,
                "redirect_on_fallback": False,
            },
            {
                "code": "it",
                "name": _("Italian"),
                "fallbacks": [
                    "en",
                ],
                "public": True,
                "hide_untranslated": True,
                "redirect_on_fallback": True,
            },
        ],
        "default": {
            "fallbacks": [
                "en",
                "it",
            ],
            "redirect_on_fallback": True,
            "public": True,
            "hide_untranslated": False,
        },
    }

    TEXT_ADDITIONAL_TAGS = ("a",)
    TEXT_ADDITIONAL_ATTRIBUTES = (
        "href",
        "class",
        "target",
        "data-test",
    )
    TEXT_HTML_SANITIZE = False

    # Redactor settings
    # REDACTOR_OPTIONS = {'lang': 'en'}
    REDACTOR_UPLOAD = "uploads/"

    REDACTOR_OPTIONS = {
        "lang": "it",
        "plugins": ["redactor_settings", "fontcolor"],
    }
